POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
    "email": "sample@gmail.com",
    "password": "ILoveRabbits"
}

###

POST http://localhost:3000/api/register HTTP/1.1
content-type: application/json

{
    "name": "Madachi",
    "email": "sample@gmail.com",
    "password": "ILoveRabbits"
}


###

POST http://localhost:3000/api/db HTTP/1.1
content-type: application/json

{
    "name": "Madachi",
    "email": "sample@gmail.com"
}

###


GET http://localhost:3000/api/desktop HTTP/1.1
Content-Type: application/json

{
    
    "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4NjYyYWZmLTMyYzctNDRlOS1iMjcyLWFkMmJkMjgyZmJhOCIsImlhdCI6MTc3NjI2MjUxOSwiZXhwIjoxNzc2MjY2MTE5fQ.V658gKLu3_mZ7zEB2Yq0GFZ0GqHhKPbHWMF41AKMnz0"
}